# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gwanjong',
            fields=[
                ('word', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
